# Generated by Django 4.2.5 on 2024-05-22 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_log', '0008_trainingsession_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macrocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('macrocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_cycle.macrocycle')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Hypertrophy', 'Hypertrophy'), ('Strength', 'Strength'), ('Peak', 'Peak'), ('Deload', 'Deload'), ('Conditioning', 'Conditioning')], default='Hypertrophy', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mesocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_cycle.mesocycle')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('phase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training_cycle.phase')),
            ],
            options={
                'unique_together': {('phase', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_log.exercise')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_cycle.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Microcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('exercise_in_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_cycle.exerciseinsession')),
            ],
            options={
                'unique_together': {('exercise_in_session', 'order')},
            },
        ),
    ]
