# Generated by Django 4.2.5 on 2024-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinsession',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='exerciseinsession',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exerciseinsession',
            name='weight',
        ),
        migrations.AddField(
            model_name='microcycle',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microcycle',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microcycle',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
