# Generated by Django 4.2.5 on 2024-06-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0002_remove_exerciseinsession_repetitions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesocycle',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='end_date',
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesocycle',
            name='macrocycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesocycles', to='training_cycle.macrocycle'),
        ),
        migrations.AlterField(
            model_name='microcycle',
            name='exercise_in_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcycles', to='training_cycle.exerciseinsession'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='mesocycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='training_cycle.mesocycle'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='training_cycle.phase'),
        ),
    ]
