# Generated by Django 4.2.5 on 2024-05-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0002_macrocycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('macrocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_cycle.macrocycle')),
            ],
        ),
        migrations.CreateModel(
            name='Microcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_cycle.phase')),
            ],
            options={
                'unique_together': {('phase', 'order')},
            },
        ),
    ]
