# Generated by Django 4.2.5 on 2024-05-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0003_phase_microcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('microcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='training_cycle.microcycle')),
            ],
            options={
                'unique_together': {('microcycle', 'order')},
            },
        ),
    ]
