# Generated by Django 4.2.5 on 2024-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0003_remove_mesocycle_end_date_remove_phase_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrocycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
