# Generated by Django 4.2.5 on 2024-08-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0008_trainingsession_description'),
        ('training_cycle', '0005_remove_macrocycle_user_macrocycle_training_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrocycle',
            name='training_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_log.traininglog'),
        ),
    ]
