# Generated by Django 4.2.5 on 2024-05-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0008_trainingsession_description'),
        ('training_cycle', '0005_exerciseprogram'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseProgram',
            new_name='ExerciseInSession',
        ),
    ]
