# Generated by Django 4.2.5 on 2024-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0006_rename_exerciseprogram_exerciseinsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinsession',
            name='reps',
        ),
        migrations.AddField(
            model_name='exerciseinsession',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinsession',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinsession',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
