# Generated by Django 4.2.5 on 2024-05-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_cycle', '0007_remove_exerciseinsession_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='name',
        ),
        migrations.AddField(
            model_name='phase',
            name='type',
            field=models.CharField(choices=[('Hypertrophy', 'Hypertrophy'), ('Strength', 'Strength'), ('Peak', 'Peak'), ('Deload', 'Deload'), ('Conditioning', 'Conditioning')], default='Hypertrophy', max_length=200),
        ),
    ]
