# Generated by Django 4.2.5 on 2024-05-20 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_cycle', '0009_mesocycle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrocycle',
            name='mesocycle',
        ),
        migrations.RemoveField(
            model_name='mesocycle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='macrocycle',
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='macrocycle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='training_cycle.macrocycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='mesocycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training_cycle.mesocycle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesocycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
