# Generated by Django 4.2.4 on 2023-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
