# Generated by Django 4.2.4 on 2023-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0002_musclegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(to='training_log.musclegroup'),
        ),
    ]
