# Generated by Django 4.2.4 on 2023-11-04 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_log', '0003_exercise_muscle_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_in_session', to='training_log.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('training_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='training_log.traininglog')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(default=1)),
                ('weight', models.FloatField()),
                ('repetitions', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('exercise_in_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_log.exerciseinsession')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinsession',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training_log.trainingsession'),
        ),
    ]
