# Generated by Django 4.2.4 on 2023-11-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0004_exerciseinsession_traininglog_trainingsession_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinsession',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='name',
            field=models.CharField(default='Log', max_length=100),
        ),
    ]
