# Generated by Django 4.2.4 on 2023-11-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0005_alter_exerciseinsession_order_alter_traininglog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise_in_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training_log.exerciseinsession'),
        ),
    ]
