# Generated by Django 4.2.4 on 2023-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0006_alter_set_exercise_in_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
