# Generated by Django 4.2.5 on 2024-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0007_trainingsession_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
