# Generated by Django 4.2.5 on 2024-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_log', '0008_trainingsession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
