# Generated by Django 4.2.5 on 2024-01-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='user_name', max_length=155),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('calves', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('thigh', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('hips', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('waist', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('chest', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('neck', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('arm', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('forearm', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
