# Generated by Django 4.2.5 on 2024-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_strengthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthrecord',
            name='percent_increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
